// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfrGvlQ3X_E8YTn_iBZEzbIRfuiVlq53A',
    appId: '1:266191834819:web:b411b25f687c094ca11c76',
    messagingSenderId: '266191834819',
    projectId: 'memoryrevived',
    authDomain: 'memoryrevived.firebaseapp.com',
    storageBucket: 'memoryrevived.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXyYFzupxlLmL4mKRgAQrUoyk566avV00',
    appId: '1:266191834819:android:3864266721f45a92a11c76',
    messagingSenderId: '266191834819',
    projectId: 'memoryrevived',
    storageBucket: 'memoryrevived.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYYa51p6AyikKD4l4NLhmOgYZhrJQyusA',
    appId: '1:266191834819:ios:ba271277306e2f03a11c76',
    messagingSenderId: '266191834819',
    projectId: 'memoryrevived',
    storageBucket: 'memoryrevived.appspot.com',
    iosBundleId: 'com.example.memoryRevived',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYYa51p6AyikKD4l4NLhmOgYZhrJQyusA',
    appId: '1:266191834819:ios:f1eb8761885aab69a11c76',
    messagingSenderId: '266191834819',
    projectId: 'memoryrevived',
    storageBucket: 'memoryrevived.appspot.com',
    iosBundleId: 'com.example.memoryRevived.RunnerTests',
  );
}
